# Generated by Django 3.2.9 on 2021-12-06 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_of_post',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
